### PR TITLE
fixes #269

### LINKED ISSUE #269: [Teams][Web] 500 at searching teams
Google Chrome Version 66.0.3359.181
Pre-conditions: 

Steps to reproduce:

1. Log in to the web app as super admin/country admin
2. Search for teamsURL | http://40.115.37.120:50000/api/v1/teams/web?country=UA&superadmin=true
3. Check results 

Expected result: there is teams list 
Actual result: there is no any team, request is returned with 500 error http://take.ms/aheV9

### PR DESCRIPTION
**Pull request by aleksandr-wemakesoftware**

### CODE REVIEW

File: backend-db/modules/db/couchdb/design/index.js [hunk 1]
```diff
@@ -171,7 +171,7 @@ const designDocs = {
                 view: {
                     map: function (doc) {
                         if (doc.$doctype === 'team') {
-                            emit(doc.name, doc);
+                            emit(doc._id, doc);
```
Comment (amangion) [inline backend-db/modules/db/couchdb/design/index.js]: We have the following code in /backend-db/modules/db/couchdb/index.js :
```
getTeam: id => adapter.getOneEntityById('Team', '_design/byTeamId/_view/view', id),
getAllTeams: () => adapter.getEntities('Team', '_design/all/_view/view', {sorted: true}),
```
You will break sorting by name with that changes "emit(doc._id, doc);"

I've already fixed this in https://github.com/letsdoitworld/World-Cleanup-Day/pull/275/files

Comment (amangion) [reply backend-db/modules/db/couchdb/design/index.js]: I suggest revert that line and use my fix.
